"""city or town

Revision ID: 42d34263db86
Revises: ffdd7be2a9e7
Create Date: 2025-03-06 22:26:03.613325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d34263db86'
down_revision = 'ffdd7be2a9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_or_town', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.drop_column('city_or_town')

    # ### end Alembic commands ###
