"""Is admin

Revision ID: 575826a1e5ff
Revises: 5d8eae7c357e
Create Date: 2025-03-05 13:53:51.085549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575826a1e5ff'
down_revision = '5d8eae7c357e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
