"""Add avatar field to User model

Revision ID: 90390c77effd
Revises: 41514a39347d
Create Date: 2025-03-06 09:20:21.463954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90390c77effd'
down_revision = '41514a39347d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
