"""Donor application

Revision ID: ed1290963cfb
Revises: 42d34263db86
Create Date: 2025-03-09 10:21:38.866926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1290963cfb'
down_revision = '42d34263db86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('wight', sa.Float(), nullable=False),
    sa.Column('habbits', sa.String(length=256), nullable=False),
    sa.Column('uidn', sa.String(length=4), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CANCELLED', 'PROCESSING', 'APPROVED', 'REJECTED', name='donorapplicationstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donor_application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donor_application_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_donor_application_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donor_application_user_id'))
        batch_op.drop_index(batch_op.f('ix_donor_application_timestamp'))

    op.drop_table('donor_application')
    # ### end Alembic commands ###
